[build-system]
requires = ["release-gitter[builder]"]
build-backend = "pseudo_builder"

[tool.release-gitter]
git-url = "https://github.com/Kampfkarren/selene"
extract-files = ["selene"]
format = "selene-{version}-{system}.zip"
exec = "chmod +x selene"