# globals
[_G]
property = true
writable = "new-fields"

[_VERSION]
property = true

[[assert.args]]
type = "any"

[[assert.args]]
type = "string"
required = "A failed assertion without a message is unhelpful to users."

[[collectgarbage.args]]
type = [
    "collect",
    "count",
    "restart",
    "setpause",
    "setstepmul",
    "step",
    "stop",
]

[[dofile.args]]
type = "string"
required = false

[[error.args]]
type = "string"
required = "Erroring without a message is unhelpful to users."

[[error.args]]
type = "number"
required = false

[[getfenv.args]]
type = "any" # TODO: function | number
required = false

[[getmetatable.args]]
type = "table"

[[ipairs.args]]
type = "table"

[[load.args]]
type = "function"

[[load.args]]
type = "string"
required = false

[[loadfile.args]]
type = "string"
required = false

[[loadstring.args]]
type = "string"

[[loadstring.args]]
type = "string"
required = false

[[module.args]]
type = "string"

[[module.args]]
type = "..."

[[newproxy.args]]
type = "bool"
required = false

[[next.args]]
type = "table"

[[next.args]]
type = "number"
required = false

[[pairs.args]]
type = "table"

[[pcall.args]]
type = "function"

[[pcall.args]]
type = "..."
required = false

[[print.args]]
type = "..."
required = false

[[rawequal.args]]
type = "any"

[[rawequal.args]]
type = "any"

[[rawget.args]]
type = "any"

[[rawget.args]]
type = "any"

[[rawset.args]]
type = "any"

[[rawset.args]]
type = "any"

[[rawset.args]]
type = "any"

[[require.args]]
type = "string"

[[select.args]]
type = "any" # TODO: "#" | number

[[select.args]]
type = "..."
required = true

[[setfenv.args]]
type = "any" # TODO: Union type, function or number

[[setfenv.args]]
type = "table"

[[setmetatable.args]]
type = "table"

[[setmetatable.args]]
type = "table"
required = false

[[tonumber.args]]
type = "any"

[[tonumber.args]]
type = "number"
required = false

[[tostring.args]]
type = "any"

[[type.args]]
type = "any"

[[unpack.args]]
type = "table"

[[unpack.args]]
type = "number"
required = false

[[unpack.args]]
type = "number"
required = false

[[xpcall.args]]
type = "function"

[[xpcall.args]]
type = "..."
required = false

# coroutine
[[coroutine.create.args]]
type = "function"

[[coroutine.resume.args]]
type = { display = "coroutine" }

[[coroutine.resume.args]]
type = "..."
required = false

[coroutine.running]
args = []

[[coroutine.status.args]]
type = { display = "coroutine" }

[[coroutine.wrap.args]]
type = "function"

[[coroutine.yield.args]]
type = "..."
required = false

# debug
[debug.debug]
args = []

# This can be used with userdata and thread too, but we don't infer those yet
[[debug.getfenv.args]]
type = "function"

[[debug.gethook.args]]
type = "any"
required = false

# debug.getinfo and friends has optional parameters *behind* it, which are unsupported
# and are instead just untyped
[[debug.getinfo.args]]
type = "any"

[[debug.getinfo.args]]
type = "any"
required = false # As mentioned above, since only one of the three arguments is required, this is necessary

[[debug.getinfo.args]]
type = "any"
required = false

[[debug.getlocal.args]]
type = "any"

[[debug.getlocal.args]]
type = "any"

[[debug.getlocal.args]]
type = "any"
required = false

[[debug.getmetatable.args]]
type = "any"

[debug.getregistry]
args = []

[[debug.getupvalue.args]]
type = "function"

[[debug.getupvalue.args]]
type = "number"

[[debug.setfenv.args]]
type = "any"

[[debug.setfenv.args]]
type = "table"

[[debug.sethook.args]]
type = "any"

[[debug.sethook.args]]
type = "any"

[[debug.sethook.args]]
type = "any"
required = false

[[debug.sethook.args]]
type = "any"
required = false

[[debug.setlocal.args]]
type = "any"

[[debug.setlocal.args]]
type = "any"

[[debug.setlocal.args]]
type = "any"

[[debug.setlocal.args]]
type = "any"
required = false

[[debug.setmetatable.args]]
type = "any"

[[debug.setmetatable.args]]
type = "table"

[[debug.setupvalue.args]]
type = "function"

[[debug.setupvalue.args]]
type = "number"

[[debug.setupvalue.args]]
type = "string"

# Since all of the arguments are optional and disregard order, the best thing to do is make them untyped.
[[debug.traceback.args]]
type = "any"
required = false

[[debug.traceback.args]]
type = "any"
required = false

[[debug.traceback.args]]
type = "any"
required = false

# io
[[io.close.args]]
type = { display = "file" }
required = false

[io.flush]
args = []

[[io.input.args]]
type = { display = "file" }
required = false

[[io.lines.args]]
type = "string"

[[io.open.args]]
type = "string"

[[io.open.args]]
type = [
    "r", "rb",
    "w", "wb",
    "a", "ab",
    "r+", "rb+",
    "w+", "wb+",
    "a+", "ab+",
]
required = false

[[io.output.args]]
type = { display = "file" }
required = false

[[io.popen.args]]
type = "string"

[[io.popen.args]]
type = [
    "r", "rb",
    "w", "wb",
    "a", "ab",
    "r+", "rb+",
    "w+", "wb+",
    "a+", "ab+",
]
required = false

[[io.read.args]]
type = "..." # TODO: Union type, constant string or number

[io.stderr]
property = true

[io.stdin]
property = true

[io.stdout]
property = true

[io.tmpfile]
args = []

[[io.type.args]]
type = { display = "potentially file-like object" }

[[io.write.args]]
type = "..."

# math
[math.huge]
property = true

[math.pi]
property = true

[[math.abs.args]]
type = "number"

[[math.acos.args]]
type = "number"

[[math.asin.args]]
type = "number"

[[math.atan.args]]
type = "number"

[[math.atan2.args]]
type = "number"

[[math.atan2.args]]
type = "number"

[[math.ceil.args]]
type = "number"

[[math.cos.args]]
type = "number"

[[math.cosh.args]]
type = "number"

[[math.deg.args]]
type = "number"

[[math.exp.args]]
type = "number"

[[math.floor.args]]
type = "number"

[[math.fmod.args]]
type = "number"

[[math.fmod.args]]
type = "number"

[[math.frexp.args]]
type = "number"

[[math.ldexp.args]]
type = "number"

[[math.ldexp.args]]
type = "number"

[[math.log.args]]
type = "number"

[[math.log10.args]]
type = "number"

[[math.max.args]]
type = "number"

[[math.max.args]]
type = "..."
required = "use of max only makes sense with more than 1 parameter"

[[math.min.args]]
type = "number"

[[math.min.args]]
type = "..."
required = "use of min only makes sense with more than 1 parameter"

[[math.modf.args]]
type = "number"

[[math.pow.args]]
type = "number"

[[math.pow.args]]
type = "number"

[[math.rad.args]]
type = "number"

[[math.random.args]]
type = "number"
required = false

[[math.random.args]]
type = "number"
required = false

[[math.randomseed.args]]
type = "number"

[[math.sin.args]]
type = "number"

[[math.sinh.args]]
type = "number"

[[math.sqrt.args]]
type = "number"

[[math.tan.args]]
type = "number"

[[math.tanh.args]]
type = "number"

# os
[os.clock]
args = []

[[os.date.args]]
type = "string"
required = false

[[os.date.args]]
type = "number"
required = false

[[os.difftime.args]]
type = "number"

[[os.difftime.args]]
type = "number"

[[os.execute.args]]
type = "string"
required = false

[[os.exit.args]]
type = "number"
required = false

[[os.getenv.args]]
type = "string"

[[os.remove.args]]
type = "string"

[[os.rename.args]]
type = "string"

[[os.rename.args]]
type = "string"

[[os.setlocale.args]]
type = "string"

[[os.setlocale.args]]
type = [
    "all",
    "collate",
    "ctype",
    "monetary",
    "numeric",
    "time",
]
required = false

[[os.time.args]]
type = "table"
required = false

[os.tmpname]
args = []

# package
[package.cpath]
property = true
writable = "full"

[package.loaded]
property = true
writable = "new-fields"

[package.loaders]
property = true
writable = "new-fields"

[[package.loadlib.args]]
type = "string"

[[package.loadlib.args]]
type = "string"

[package.path]
property = true
writable = "full"

[package.preload]
property = true
writable = "new-fields"

[[package.seeall.args]]
type = "table"

# string
[[string.byte.args]]
type = "string"

[[string.byte.args]]
type = "number"
required = false

[[string.byte.args]]
type = "number"
required = false

[[string.char.args]]
type = "number"
required = "string.char should be used with an argument despite it not throwing"

[[string.char.args]]
type = "..."
required = false

[[string.dump.args]]
type = "function"

[[string.find.args]]
type = "string"

[[string.find.args]]
type = "string" # TODO: Pattern type?

[[string.find.args]]
type = "number"
required = false

[[string.find.args]]
type = "bool"
required = false

[[string.format.args]]
type = "string"

[[string.format.args]]
type = "..."
required = "string.format should only be used for strings that need formatting"

[[string.gmatch.args]]
type = "string"

[[string.gmatch.args]]
type = "string"

[[string.gsub.args]]
type = "string"

[[string.gsub.args]]
type = "string" # TODO: Pattern type?

[[string.gsub.args]]
type = "any"

[[string.gsub.args]]
type = "number"
required = false

[[string.len.args]]
type = "string"

[[string.lower.args]]
type = "string"

[[string.match.args]]
type = "string"

[[string.match.args]]
type = "string" # TODO: Pattern type?

[[string.match.args]]
type = "number"
required = false

[[string.rep.args]]
type = "string"

[[string.rep.args]]
type = "number"

[[string.reverse.args]]
type = "string"

[[string.sub.args]]
type = "string"

[[string.sub.args]]
type = "number"

[[string.sub.args]]
type = "number"
required = false

[[string.upper.args]]
type = "string"

# table
[[table.concat.args]]
type = "table"

[[table.concat.args]]
type = "string"
required = false

[[table.concat.args]]
type = "number"
required = false

[[table.concat.args]]
type = "number"
required = false

[[table.insert.args]]
type = "table"

[[table.insert.args]]
type = "any"

[[table.insert.args]]
type = "any"
required = false

[[table.maxn.args]]
type = "table"

[[table.remove.args]]
type = "table"

[[table.remove.args]]
type = "number"
required = false

[[table.sort.args]]
type = "table"

[[table.sort.args]]
type = "function"
required = false
