[selene]
base = "lua51"
name = "roblox"

[selene.structs.EnumItem.Name]
property = true

[selene.structs.EnumItem.Value]
property = true

[selene.structs.Event.Connect]
method = true

[[selene.structs.Event.Connect.args]]
type = "function"

[selene.structs.Event.Wait]
method = true
args = []

[selene.structs.Instance."*"]
any = true

[[bit32.arshift.args]]
type = "number"

[[bit32.arshift.args]]
type = "number"

[[bit32.band.args]]
type = "number"

[[bit32.bnot.args]]
type = "number"

[[bit32.bor.args]]
type = "..."

[[bit32.btest.args]]
type = "..."

[[bit32.bxor.args]]
type = "..."

[[bit32.extract.args]]
type = "number"

[[bit32.extract.args]]
type = "number"

[[bit32.extract.args]]
type = "number"
required = false

[[bit32.replace.args]]
type = "number"

[[bit32.replace.args]]
type = "number"

[[bit32.replace.args]]
type = "number"
required = false

[[bit32.lrotate.args]]
type = "number"

[[bit32.lrotate.args]]
type = "number"

[[bit32.lshift.args]]
type = "number"

[[bit32.lshift.args]]
type = "number"

[[bit32.rrotate.args]]
type = "number"

[[bit32.rrotate.args]]
type = "number"

[[bit32.rshift.args]]
type = "number"

[[bit32.rshift.args]]
type = "number"

[[BrickColor.new.args]]
type = "any"

[[BrickColor.new.args]]
type = "number"
required = false

[[BrickColor.new.args]]
type = "number"
required = false

[[BrickColor.palette.args]]
type = "number"

[BrickColor.random]
args = []

# BrickColor colors
[BrickColor.Black]
args = []

[BrickColor.Blue]
args = []

[BrickColor.DarkGray]
args = []

[BrickColor.Gray]
args = []

[BrickColor.Green]
args = []

[BrickColor.Red]
args = []

[BrickColor.White]
args = []

[BrickColor.Yellow]
args = []

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "number"
required = false

[[CFrame.fromAxisAngle.args]]
type = { display = "Vector3" }

[[CFrame.fromAxisAngle.args]]
type = "number"

[[CFrame.fromEulerAnglesXYZ.args]]
type = "number"

[[CFrame.fromEulerAnglesXYZ.args]]
type = "number"

[[CFrame.fromEulerAnglesXYZ.args]]
type = "number"

[[CFrame.fromMatrix.args]]
type = { display = "Vector3" }

[[CFrame.fromMatrix.args]]
type = { display = "Vector3" }

[[CFrame.fromMatrix.args]]
type = { display = "Vector3" }

[[CFrame.fromMatrix.args]]
type = { display = "Vector3" }

[[CFrame.fromOrientation.args]]
type = "number"

[[CFrame.fromOrientation.args]]
type = "number"

[[CFrame.fromOrientation.args]]
type = "number"

[[Color3.fromRGB.args]]
type = "number"

[[Color3.fromRGB.args]]
type = "number"

[[Color3.fromRGB.args]]
type = "number"

[[Color3.fromHSV.args]]
type = "number"

[[Color3.fromHSV.args]]
type = "number"

[[Color3.fromHSV.args]]
type = "number"

[[Color3.new.args]]
type = "number"
required = false

[[Color3.new.args]]
type = "number"
required = false

[[Color3.new.args]]
type = "number"
required = false

[[Color3.toHSV.args]]
type = { display = "Color3" }
required = false

[[ColorSequence.new.args]]
type = "any"

[[ColorSequence.new.args]]
type = { display = "Color3" }
required = false

[coroutine.isyieldable]
args = []

[[debug.profilebegin.args]]
type = "string"

[debug.profileend]
args = []

[[delay.args]]
type = "number"

[[delay.args]]
type = "function"

[[DockWidgetPluginGuiInfo.new.args]]
type = { display = "InitialDockState" }
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "bool"
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "bool"
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "number"
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "number"
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "number"
required = false

[[DockWidgetPluginGuiInfo.new.args]]
type = "number"
required = false

[[Instance.new.args]]
type = "string" # This is changed at generate time

[[math.clamp.args]]
type = "number"

[[math.clamp.args]]
type = "number"

[[math.clamp.args]]
type = "number"

[[math.log.args]]
type = "number"

[[math.log.args]]
type = "number"
required = false

[[math.sign.args]]
type = "number"

[[math.noise.args]]
type = "number"

[[math.noise.args]]
type = "number"
required = false

[[math.noise.args]]
type = "number"
required = false

[[NumberRange.new.args]]
type = "number"

[[NumberRange.new.args]]
required = false
type = "number"

[[NumberSequence.new.args]]
type = "any"

[[NumberSequence.new.args]]
type = "number"
required = false

[[NumberSequenceKeypoint.new.args]]
type = "number"

[[NumberSequenceKeypoint.new.args]]
type = "number"

[[NumberSequenceKeypoint.new.args]]
type = "number"
required = false

[[PhysicalProperties.new.args]]
type = "any"

[[PhysicalProperties.new.args]]
type = "number"
required = false

[[PhysicalProperties.new.args]]
type = "number"
required = false

[[PhysicalProperties.new.args]]
type = "number"
required = false

[[PhysicalProperties.new.args]]
type = "number"
required = false

[[Random.new.args]]
type = "number"
required = false

[[Ray.new.args]]
type = { display = "Vector3" }

[[Ray.new.args]]
type = { display = "Vector3" }

[[Rect.new.args]]
type = "any"

[[Rect.new.args]]
type = "any"

[[Rect.new.args]]
type = "any"
required = false

[[Rect.new.args]]
type = "any"
required = false

[[Region3.new.args]]
type = { display = "Vector3" }

[[Region3.new.args]]
type = { display = "Vector3"}

[[Region3int16.new.args]]
type = { display = "Vector3" }

[[Region3int16.new.args]]
type = { display = "Vector3"}

[settings]
args = []

[shared]
property = true
writable = "new-fields"

[[spawn.args]]
type = "function"

[[string.split.args]]
type = "string"

[[string.split.args]]
type = "string"
required = false

[[table.find.args]]
type = "table"

[[table.find.args]]
type = "any"

[[table.find.args]]
type = "number"
required = false

[[table.create.args]]
type = "number"

[[table.create.args]]
type = "any"
required = false

[[table.move.args]]
type = "table"

[[table.move.args]]
type = "number"

[[table.move.args]]
type = "number"

[[table.move.args]]
type = "number"

[[table.move.args]]
type = "table"
required = false

[[table.pack.args]]
type = "..."

[[table.unpack.args]]
type = "table"

[[table.unpack.args]]
type = "number"
required = false

[[table.unpack.args]]
type = "number"
required = false

[tick]
args = []

[time]
args = []

[[TweenInfo.new.args]]
type = "number"
required = false

[[TweenInfo.new.args]]
type = { display = "EasingStyle" }
required = false

[[TweenInfo.new.args]]
type = { display = "EasingDirection" }
required = false

[[TweenInfo.new.args]]
type = "number"
required = false

[[TweenInfo.new.args]]
type = "bool"
required = false

[[TweenInfo.new.args]]
type = "number"
required = false

[[typeof.args]]
type = "any"

[[UDim.new.args]]
type = "number"

[[UDim.new.args]]
type = "number"

[[UDim2.new.args]]
type = "any"
required = false

[[UDim2.new.args]]
type = "any"
required = false

[[UDim2.new.args]]
type = "any"
required = false

[[UDim2.new.args]]
type = "any"
required = false

[[UDim2.fromOffset.args]]
type = "number"

[[UDim2.fromOffset.args]]
type = "number"

[[UDim2.fromScale.args]]
type = "number"

[[UDim2.fromScale.args]]
type = "number"

[UserSettings]
args = []

[[utf8.char.args]]
type = "number"
required = "utf8.char should be used with an argument despite it not throwing"

[[utf8.char.args]]
type = "..."
required = false

[[utf8.codepoint.args]]
type = "string"

[[utf8.codepoint.args]]
type = "number"
required = false

[[utf8.codepoint.args]]
type = "number"
required = false

[[utf8.codes.args]]
type = "string"

[[utf8.graphemes.args]]
type = "string"

[[utf8.graphemes.args]]
type = "number"
required = false

[[utf8.graphemes.args]]
type = "number"
required = false

[[utf8.len.args]]
type = "string"

[[utf8.len.args]]
type = "number"
required = false

[[utf8.len.args]]
type = "number"
required = false

[[utf8.nfcnormalize.args]]
type = "string"

[[utf8.nfdnormalize.args]]
type = "string"

[[utf8.offset.args]]
type = "string"

[[utf8.offset.args]]
type = "number"
required = false

[[utf8.offset.args]]
type = "number"
required = false

[[utf8.charpattern]]
property = true

[[Vector2.new.args]]
type = "number"
required = false

[[Vector2.new.args]]
type = "number"
required = false

[[Vector2int16.new.args]]
type = "number"
required = false

[[Vector2int16.new.args]]
type = "number"
required = false

[[Vector3.FromAxis.args]]
type = { display = "Axis" }

[[Vector3.FromNormalId.args]]
type = { display = "NormalId" }

[[Vector3.new.args]]
type = "number"
required = false

[[Vector3.new.args]]
type = "number"
required = false

[[Vector3.new.args]]
type = "number"
required = false

[[Vector3int16.new.args]]
type = "number"
required = false

[[Vector3int16.new.args]]
type = "number"
required = false

[[Vector3int16.new.args]]
type = "number"
required = false

[[warn.args]]
type = "string"

[[warn.args]]
type = "..."
required = false

[[wait.args]]
type = "number"
required = false

# Removed stuff
[[collectgarbage.args]]
type = ["count"]

[dofile]
removed = true

[load]
removed = true

[loadfile]
removed = true

[module]
removed = true

[debug.debug]
removed = true

[debug.getfenv]
removed = true

[debug.gethook]
removed = true

[debug.getinfo]
removed = true

[debug.getmetatable]
removed = true

[debug.getregistry]
removed = true

[debug.getupvalue]
removed = true

[debug.setfenv]
removed = true

[debug.sethook]
removed = true

[debug.setlocal]
removed = true

[debug.setmetatable]
removed = true

[debug.setupvalue]
removed = true

[io]
removed = true

[os.clock]
removed = true

[os.execute]
removed = true

[os.exit]
removed = true

[os.getenv]
removed = true

[os.remove]
removed = true

[os.rename]
removed = true

[os.setlocale]
removed = true

[os.tmpname]
removed = true
