name: Test selene
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo clippy
    - name: Run Rustfmt
      run: cargo fmt -- --check
    - name: Run tests (selene, all features)
      run: cargo test
      working-directory: selene
    - name: Run tests (selene, no features)
      run: cargo test --no-default-features
      working-directory: selene
    - name: Run tests (selene-lib, all features)
      run: cargo test
      working-directory: selene-lib
    - name: Run tests (selene-lib, no features)
      run: cargo test --no-default-features
      working-directory: selene-lib
    - name: Run exhaustive check tests
      run: rustup run nightly cargo test --features force_exhaustive_checks
      working-directory: selene-lib
