name: Test selene
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests (selene, all features)
      run: cargo test -- --nocapture
      working-directory: selene
    - name: Run tests (selene, no features)
      run: cargo test --no-default-features -- --nocapture
      working-directory: selene
    - name: Run tests (selene-lib, all features)
      run: cargo test
      working-directory: selene-lib
    - name: Run tests (selene-lib, no features)
      run: cargo test --no-default-features
      working-directory: selene-lib
  # Remove this when non_exhaustive_omitted_patterns_lint is made stable in the next Rust version
  test_exhaustive_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly for exhaustive check tests
      uses: dtolnay/rust-toolchain@nightly
    - name: Run exhaustive check tests
      run: cargo check --features force_exhaustive_checks
      working-directory: selene-lib
  lint:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Rustfmt
      run: cargo fmt -- --check
      if: success() || failure()